### ISSUE TITLE
Project has no stable releases

### ISSUE THREAD

**Issue by TheBnl** [silvershop/silvershop-coloredvariations#11]
Currently there is only a dev-master branch with no stable releases. This creates issues when updating modules on a SS3 project. Could commit [298fcac04](https://github.com/silvershop/silvershop-coloredvariations/tree/298fcac04b7c82ccd3bad450e088e5752f703f93) be tagged as version e.g. 1.0 or 0.1 so we have a stable release for SS3? 

Thanks! 👍

**Comment by wilr** [comment]
Done, tagged `1.0.0`, a `1` branch exists for bug fixes and `2.0.0` is tagged for SS4

**Comment by TheBnl** [comment]
Cheers thanks!
